export enum ExpenseStatus {
  PENDING_TEACHER_REVIEW = 'PENDING_TEACHER_REVIEW',
  PENDING_DEAN_APPROVAL = 'PENDING_DEAN_APPROVAL',
  PENDING_DISBURSEMENT = 'PENDING_DISBURSEMENT',
  DISBURSED = 'DISBURSED',
  REJECTED = 'REJECTED'
}