export enum EventStatus {
  UPCOMING = 'UPCOMING',
  ONGOING = 'ONGOING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  ARCHIVED = 'ARCHIVED',
}

export enum EventFundingType {
  SCHOOL = 'SCHOOL',
  FACULTY = 'FACULTY',
  OUTSOURCE = 'OUTSOURCE',
}