export enum EventStatus {
  PENDING_DEAN_APPROVAL = 'PENDING_DEAN_APPROVAL',
  PENDING_FINANCE_APPROVAL = 'PENDING_FINANCE_APPROVAL',
  UPCOMING = 'UPCOMING',
  ONGOING = 'ONGOING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  ARCHIVED = 'ARCHIVED',
  REJECTED = "REJECTED",
}

export enum EventFundingType {
  SCHOOL = 'SCHOOL',
  FACULTY = 'FACULTY',
  OUTSOURCE = 'OUTSOURCE',
  PROJECT = 'PROJECT',
}