export enum AuditAction {
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
  DISBURSE = 'DISBURSED',
  SUBMIT = "SUBMIT",
  RESUBMIT = 'RESUBMIT',
}

export enum ExpenseStatus {
  PENDING_TEACHER_REVIEW = 'PENDING_TEACHER_REVIEW',
  PENDING_DEAN_APPROVAL = 'PENDING_DEAN_APPROVAL',
  PENDING_DISBURSEMENT = 'PENDING_DISBURSEMENT',
  DISBURSED = 'DISBURSED',
  REJECTED = 'REJECTED'
}

export enum PaidMethod {
  CASH = 'CASH',
  BANK_TRANSFER = 'BANK_TRANSFER'
}