name: Continuous Deployment to Firebase

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Enable Corepack
        run: corepack enable[cite: 14]

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --immutable[cite: 14]

      - name: Derive appropriate SHAs for affected commands
        uses: nrwl/nx-set-shas@v4

      - name: Deploy Affected Applications Only
        run: yarn nx affected -t deploy --token "${{ secrets.FIREBASE_TOKEN }}"