name: Continuous Deployment to Firebase

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{secrets.ADMIN_RELEASE_TOKEN}}

      - name: Enable Corepack
        run: corepack enable

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Bump Version & Update Changelog
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          npx standard-version --skip.tag

      - name: Commit & Push Changelog
        run: |
          git add CHANGELOG.md package.json
          git commit -m "chore(release): update version and changelog [skip ci]" || echo "No changes to commit"
          git push origin main

      - name: Install Firebase CLI globally
        run: npm install -g firebase-tools

      - name: Derive appropriate SHAs for affected commands
        uses: nrwl/nx-set-shas@v4

      - name: Deploy Affected Applications Only
        run: yarn nx affected -t deploy --token "${{ secrets.FIREBASE_TOKEN }}"